### ISSUE TITLE
一例模型视图没有同步的 case

### ISSUE THREAD

**Issue by Dafrok** [baidu/san-store#10]
## 环境

- Chrome@58
- san@3.0.3 （因为 3.1.0-alpha 没有 cdn 版本，在线展示只好先用这个凑合，本地可用 3.1.0-alpha 复现）
- san-store@1.0.1
- san-update@2.1.0

## 复现用例

https://codepen.io/Dafrok/pen/zwMgzp

## 逻辑描述

复现场景较为复杂。

### store 属性

1. **root**：该属性负责存放节点树，每个 `{name<String>, children<Array>}` 结构的对象视为一个节点，`children` 存放该节点的子节点。
2. **path**：该节点负责存放被激活的节点路径。暂称为 *激活路径*。如 `store.getState('root.children[1]') 被激活时，path 属性的值为 `'root.children[1]'`。

### 组件

1. **根组件**：该组件负责 connect store和处理业务逻辑。组件含有一个按钮，点击按钮会向 store 的 *激活路径* push 一个节点对象。
2. **树形结构组件**：根据 store 的 root 属性输出一个节点树。点击某个节点可以改变 *激活路径* 为这个节点的路径。
3. **列表组件**：仅展示 *激活路径* 的所属节点的子节点。

## 期望输出

点击 **树形结构组件** 激活一个节点，然后点击『插入节点』按钮后，**树形结构组件** 被激活的节点下插入一个节点，同时 **列表组件** 也插入一个节点。

## 实际输出

点击 **树形结构组件** 激活一个节点，然后点击『插入节点』按钮后，**树形结构组件** 被激活的节点下插入一个节点，而 **列表组件** 没有更新。再次激活该节点时，被插入的节点才更新到视图上。

**Comment by errorrik** [comment]
这个不是bug。

你组件里用了 `current` 作为computed data，这里面通过 `this.data.get('path')` 进行计算。所以 `current` 依赖于 `path`。

但是，点击插入节点的时候，变更的是 `root`，`current` 依赖的 `path`并没有发生变化，所以视图没有更新。

所以，你需要让 `current` 中对它实际依赖的数据项显示引用。我随手写了个例子，有bug，仅为说明问题。

```
computed: {
    current () {
      let path = this.data.get('path');
      let data = this.data.get('root');

      if (data && path) {
          path = path
            .replace(/\[([0-9]+)\]/g, function (match, $1) {
                return '.' + $1 + '.';
            })
            .replace(/\.$/, '')
            .split('.')
            .slice(1);
          for (let i = 0; i < path.length; i++) {
            data = data[path[i]];
          }

          return data;
      }

      return null;
    }
  }
```

**Comment by Dafrok** [comment]
已经确认是这个问题。我需要在计算属性里声明依赖需要单独写一行 `this.data.get(DEPENDENCY)` 声明依赖 ，即使用不到它。这样一来会导致 `data.get` 有了 *获取数据* 和 *声明依赖* 双重语义，直觉上会让人混乱。这里建议在 [文档的相关部分](https://ecomfe.github.io/san/tutorial/component/#计算数据) 着重强调这个语义，或者修改为一个可读性更高的声明依赖的范式，比如加入一个声明依赖函数 `dependOn([...DEPENDENCIES])`，这里抛砖引玉，不做过多解读了。
