### ISSUE TITLE
求教关于单例store与侵入型connect的最佳实践

### ISSUE THREAD

**Issue by yanni4night** [baidu/san-store#12]
首先，虽然store是可以自行创建的，但connect却只支持全局的这个单例store。

其次，*connect.san()(MyComponent) === MyComponent*，这是否意味着MyComponent这样一个class定义，就只能为全局一个store服务？

在多频道（Tab）这样的 **共享内存** 但业务数据却  **严格分离** 的应用中，如何设计可使san-store的应用最合理高效？

**Comment by errorrik** [comment]
san 的组件是可继承的，所以你完全可以connect一个继承的组件。

至于connect为啥不自动派生一个独立的组件类呢？因为如果你在一个module里声明了组件并export connect结果，那意味着这东西其实是被赋予业务场景的，自动派生就没必要了。

至于Tab这种很独立的组件，应该先有一个业务无关的独立Tab组件，然后有多个被connect的派生类
