### ISSUE TITLE
移除store上的dispatch和fire等方法

### ISSUE THREAD

**Issue by otakustay** [baidu/san-store#2]
API设计如下：

```js
import {createStore} from 'san-store';

let {store, dispatch, subscribe} = createStore(...);
```

redux的`dispatch`和`subscribe`是放在store上的，给人一种需要有this的感觉。我觉得直接以函数的形式返回会更好一些，内部实现上也不用依赖mini-event

**Comment by errorrik** [comment]
看起来 createStore 还是要返回一个上面有 dispatch 和 subscribe 的对象。如果用的不是 esnext 语法，还是会变成 `var store = createStrore(); store.dispatch(...)` 。

我同意 dispatch 和 subscribe 方法去 this，不依赖 mini-event。

**Comment by otakustay** [comment]
我的想法是返回一个`{store, dispatch, subscribe}`的对象，区别在于store和dispatch是平级的，所以没有esnext就是

```js
var storeContext = createStore();
var store = store.store;
var dispatch = store.dispatch;
```

**Comment by errorrik** [comment]
看着很难理解诶，createStore里面返回的不是一个store，而是一堆东西

**Comment by otakustay** [comment]
同意不太好理解，其实返回的是store全家桶……但是store本身因为有get方法，传达出的是有状态的感觉，因此很容易被人认为dispatch和subscribe必须以store为this才能用，进而更多人会在需要dispatch的时候把store直接丢进组件等不应该引用store的地方去，我只是想阻止这个情况

**Comment by errorrik** [comment]
按照全家桶的语意，就应该是

```
var appStateManager = createAppStateManager();
var store = appStateManager.store;
var dispatch = appStateManager.dispatch;
```

但这样看的比较繁琐，也没必要。本来app state manage就是围绕store进行的。所以

> 需要dispatch的时候把store直接丢进组件等不应该引用store的地方去，我只是想阻止这个情况

我觉得：

1. dispatch实现时脱离this
2. 通过connect可以在组件上添加dispatch action的方法到组件的actions property去，类似redux connect的mapToDispatch功能
3. 我觉得这个是很重要的，大多数人都是照例子抄的，所以san-store我会实现一个todos的example

**Comment by otakustay** [comment]
OK，无论是文档还是示例，我们只要别让人直接把store灌进组件里就好
