### ISSUE TITLE
不要让Action可以继续dispatch

### ISSUE THREAD

**Issue by otakustay** [baidu/san-store#3]
理由有几点：

1. 我们先做最小功能的集合，这个需求后续真的存在的话再加不迟，现在就加上只会导致去不掉
2. 本身Action中继续dispatch是可能引起死循环的，redux中在subscribe章节特别说了这个问题
3. Action本身是同步的，这意味着他应该能一次性完成所有的工作，那么同步再通过dispatch触发另一个同步似乎并没有意义，Action不应该是作为“数据修改的逻辑”的复用单元
4. 避免因为dispatch的存在让人在Action中进行异步操作之后再进行dispatch

**Comment by errorrik** [comment]
首先，我是反对 action 中直接 dispatch 另一个 action 的。

但是，要不要让 action 可以继续 dispatch 呢？这里有个假设：是否 action 应该承担所有 controller view 对应用状态数据相关的职责。

简单的例子，我要获取一个列表，是要

1. dispatch 一个 get-list action？
2. 调用一个 request 方法，在 异步返回时 dispatch？

如果推荐 2 的话，这个问题就可以中止了。

如果推荐 1，那么我们势必会碰到 start request 时把 loading 设置成true，request 返回时把 loading 设置成 false 然后设置 list。

好了，这个场景，如果不能继续 dispatch，怎么玩？

**Comment by otakustay** [comment]
从macro的那个PR上来看，我的思路就是action是同步的，因此我的选择就是2

如果我们希望在store上设计一个允许异步的东西，那么这个东西我认为也不会是现在的形态，它应该满足以下条件：

1. 可以在一系列的异步过程中多次提交对store的修改（如打开进度条 - 请求数据 - 更新数据 - 关闭进度条，这一过程涉及3次的store修改，2次进度条1次数据更新）
2. 这一系列的store修改必须能串起来，至少从日志上作为一个整体能看出来
3. 每次修改都要基于修改进行时的store数据，避免因为异步导致的数据脱节和乱序，比如连续点击列表中的每一项，发起了N个异步，无论这异步哪个先完成，必须只有用户最后点击的那个得以保留

那么就肯定不能是我们现在的这种Action的形式，现在的形式不满足上面的任意一条，即便使用Action中继续dispatch来提供第1条的能力，第2和3都会有问题

上面这个描述的东西，其实我也一早就想提一提的，但担心会将架构复杂化所以没说出来……在redux中其中是ActionCreator，我更倾向于称之为一个Transaction（名字随意了……），我对这个东西的描述很简单，也是我在sanv设计中的一个核心：

```js
function *transaction({Object} data, {*} payload) => Action
```

首先这是一个generator，它在运行过程中可以yield出任意多个Action，最后一个Action需要使用return以标识一个事务完成，这样就可以把一次iterate过程的东西归为一组串起来，同时因为返回的是Action（一个函数），调用这个Action时再提供当前的store数据以保持数据是同步的不会因为异步而脱节

这个设计因为需要generator所以在没有babel的情况下支持度很差，但从对ES Next的应用上来说我认为不失为一个亮点，具备推广（打广告）上的意义

如果不希望在框架上使用generator，可以设计为`function ({Object} data, {*} payload, {Function} report`这样的形式用callback解决，但编码体验上肯定没generator来得好

**Comment by Justineo** [comment]
Vuex 里同步的修改叫 mutation，异步、组合的修改叫 action……mutation 是可以列出来的所以 trackable。

**Comment by otakustay** [comment]
> mutation 是可以列出来的所以 trackable。

无论是redux还是vuex都存在的一个问题是，他们只有最后的那个同步的更新是可以跟踪的，但是当你看整个state的变化过程的时候，只能看到哪些reducer/mutation运行了，却不知道为什么而运行，最初源自哪里，因为它们不会将reducer/mutation再映射到action creator/action上去，也就更不可能再进一步映射到某个组件的某个事件、某个用户的操作上去了，即它只解释了what和when而没有解释how、who和why

我期待的是在应用级的架构里，可以让state的变化回根溯源，依次从同步的更新推导到异步的事务，到组件的事件，到用户的行为，我称这个东西为“线索”，难度比较大但如果可以做成通过devtool等展现出一个完事的线索追溯的图来，会是我们很大的一个优势

**Comment by errorrik** [comment]
你们没娃的继续，我明早再来挖坟

**Comment by errorrik** [comment]
灰大提的一个过程（或者说一个流），其实挺麻烦的，不单设计自己本身的异步性，还有两个同时运行的过程怎么处理（比如用户点了a按钮又抽风点了b按钮）。我觉得需要更高的更复杂的抽象来解决。这个问题我们是放放还是在这讨论？

**Comment by otakustay** [comment]
> 灰大提的一个过程（或者说一个流），其实挺麻烦的，不单设计自己本身的异步性，还有两个同时运行的过程怎么处理（比如用户点了a按钮又抽风点了b按钮）。我觉得需要更高的更复杂的抽象来解决。这个问题我们是放放还是在这讨论？

在记录和串联这个环节上能放放，但是我认为异步的逻辑放在哪个环节这是我们要去定义的，不能让开发者到处乱来

**Comment by errorrik** [comment]
ok，回到简单的例子，我要获取一个列表，是要

1. dispatch 一个 get-list action？
2. 调用一个 request 方法，在 异步返回时 dispatch？

@otakustay 

你选了2，那意味着业务组件开发者是自由的。现在我们想收回这个自由，那总得给个出口，这个出口应该是什么。（不得不佩服vuex的设计，你要异步就dispatch action要同步就commit mutation，其实同步也可以dispatch action然后action内直接commit mutation，很清晰）

**Comment by otakustay** [comment]
整个流程无非是

> 用户操作 - 程序的事件 - 业务的逻辑 - 状态的变化

我们只要考虑这4个东西各自有各自的固定模式，不要相互穿插（前期最好也不要能选择性省掉一步）就好，那么1不是程序性的，2是san管的，4是Action，所以要给3一个名字和定义，并且在san-store把这些串起来

**Comment by errorrik** [comment]
所以才佩服vuex的设计

- 业务的逻辑：action
- 状态的变化：mutation

**Comment by otakustay** [comment]
嘛按我说的就是

- 业务逻辑：transaction
- 状态变化：action

我唯一不同的是把transaction搞成了generator而已……

**Comment by errorrik** [comment]
其实我说的是佩服人家对语义的把握能力，完全没歧义，顾名思义的很直接。毕竟人家英语基本等于母语了。transaction就让我一下想起了事务，然后想起了隔离性原子性一致性。。。

**Comment by otakustay** [comment]
大不了直接让名字保持一致得了……确实transaction有多次提交的话会显得奇怪是真的

**Comment by errorrik** [comment]
保持一致像抄袭。。。

**Comment by errorrik** [comment]
虽然我是backer，但是也没脸抄。。。

**Comment by otakustay** [comment]
那么暴力点业务逻辑叫logic，更新叫action

**Comment by errorrik** [comment]
see #6
