### ISSUE TITLE
简化get方法

### ISSUE THREAD

**Issue by otakustay** [baidu/san-store#4]
从Store的层面上来说，只需要`getData()`方法返回整个数据就行，一个支持path的get方法出现在connect相关的模块里更合适

**Comment by errorrik** [comment]
ok，支持path的get方法只是我实现更新方法时想用来判断是否===而已

**Comment by errorrik** [comment]
感受了下，支持path的get方法还是要有的。

1. 省的使用者出错。比如我要拿user.name，使用者get().user.name，当开始user不存在时就报错了
2. 使用者可能不清醒的去设置值，get().user.name = 'xxx'，通过get方法可以返回clone。（当然一个大的get也能返回clone，但是成本比较高）

**Comment by otakustay** [comment]
> 省的使用者出错。比如我要拿user.name，使用者get().user.name，当开始user不存在时就报错了

user不存在难道不应该报错吗？

**Comment by errorrik** [comment]
比如我store里面存了一项listpage，表示的是列表页的各种信息（每页条数、筛选、页码等），后端列表数据返回的时候要dispatch action。这时候action需要判断我是不是当前页面（因为我可能点第二页又很快点第三页，这时候两个请求，只有一个是需要更新store里数据的）。这时候我这么写action

```js
function ({page, listData}) {
    if (this.get().listpage.currentPage === page) {
        return macro().set('listpage.data', listData)
    }
}
```

但是，用户可能点了编辑页，然后这个页面跳走了，listpage这一项被清空了，这时候就很麻烦了，我总不能每个地方都states = get(); states.listpage && states.listpage.currentPage 去判断

**Comment by otakustay** [comment]
估计用不了多久js就会有这个case的语法支持了……

那为啥不把get提供为一个工具方法：

```
let state = get();
if (visit(state, 'listPage.currentPage') == null) {
}
```

**Comment by errorrik** [comment]
说白了还是接受成本更低嘛，而且我也想get return的是clone，省的有人改出问题。clone所有states成本太高了

**Comment by errorrik** [comment]
说实话，clone一个list成本也挺高的，妈蛋

**Comment by otakustay** [comment]
我们还是别clone了，get就给人拿着用，出事了不管得了- -

**Comment by errorrik** [comment]
好吧，那文档里强调下好了。其实一般人不会犯简单错误，就是怕connect到组件的，由于组件代码里的set data导致对象发生变化。

至于get方法，我觉得不能指望js有这个语法case的支持，因为短期内支持了也没法用。。。

**Comment by errorrik** [comment]
我觉得应该叫getState。有两种方案

1. store上不提供getState方法，只提供get方法，在action里提供getState方法
2. store上也提供getState方法，action里也提供getState方法

**Comment by Dafrok** [comment]
所以最后是怎样做了？我发现目前的版本 store.get 已经变成了 getState，而 Action 参数的 getState 方法不能返回结果，而文档上却说 Action 参数中的 getState 函数和上下文无关，有点迷。

```javascript
import {store} from 'san-store'
import {builder} from 'san-update'

// 初始化一个 foo 变量
store.addAction('foo', payload => builder().set('foo', true))
store.dispatch('foo')

// 打印 foo
store.addAction('showFoo', (payload, {getState}) => console.log(getState('foo')))
store.dispatch('showFoo') // => undefined
store.getState('foo') // => true
```
