### ISSUE TITLE
强调connect型的组件和视图型组件的分离

### ISSUE THREAD

**Issue by otakustay** [baidu/san-store#5]
从一个应用系统的角度来看，将“与store进行连接”和“视图展现”混搭起来似乎并不是一个好的实践，store承载着应用状态必然与业务关联，而业务与视图分离在任何架构中都是一个准则，因此像这样的代码还是避免出现：

```html
<template>
<div>
    <select value="{{year}}>
        <option>...</option>
    </select>
</div>
</template>
<script>
@connect(...)
class Calendar extends Component {

}
</script>
```

这是一个将日历这样的视图组件和业务上与store连接混合在一起的，在导致业务逻辑（各种mapping）和视图混杂的情况下，同时也让视图部分无法被复用，因此一种更好的方式是：

```js
import {Calendar} from '../Calendar/index';
import {connect} from 'san-store';

export default connect(mapToData)(Calendar)
```

这样子将视图部分（日历）和业务部分（connect）分离干净

当然我们可以考虑提供一些通用的connect相关的组件，比如是否能这样写：

```html
<s-connector>
    <slot name="mapToData">
        <s-map from="..." to="..." />
        <s-map from="..." to="..." />
        <s-map from="..." to="..." />
    </slot>
    <s-calendar ... />
</s-connector>
```

**Comment by errorrik** [comment]
我觉得：

1. 日历这样的视图组件就应该干净清透没问题的
2. connect 是应该返回一个新组件类，不过我依然觉得，任何地方都不应该对日历这样的基础功能视图组件进行connect
3. connect 这样一个行为采用视图声明感觉怪怪的

**Comment by otakustay** [comment]
那就不需要connector这样的组件，我们只需要在文档之类的地方将这个强调出来即可
