### ISSUE TITLE
异步

### ISSUE THREAD

**Issue by errorrik** [baidu/san-store#6]
1. 现在的action是完全同步的，update state由action负责
2. 希望san-store为应用开发提供一个无论同步或异步过程的统一出口

所以要有异步模型。他山之石可以攻玉，看看别人都咋玩的

### vuex

vuex是action是异步的，mutation是同步的，mutation等于我们的action，说白了就是两个抽象，一个同步一个异步

### redux

dispatch方法接收一个action对象，或者一个函数，当它是函数时，函数接收disaptch和getState参数。

也就是说，dispatch方法接收action对象时，过程是同步的，走进reducers，然后update state。如果是函数，则时机就函数自己看着办了，函数里面可以来个promise，在未来某个时候再调用dispatch方法。

```js
function innerFetchTodos(category) {
    return dispatch => {
        dispatch(requestTodos(category));
        return service.todos(category)
            .then(todos => dispatch(receiveTodos(category, todos)))
    };
}

function requestTodos(category) {
    return {
        type: ActionType.REQUEST_TODOS,
        payload: {
            category
        }
    };
}

function receiveTodos(category, todos) {
    return {
        type: ActionType.RECEIVE_TODOS,
        payload: {
            category,
            todos
        }
    };
}

export function fetchTodos(category) {
    return (dispatch, getState) => {
        let state = getState();

        if (!state.todos.isFetching) {
            return dispatch(innerFetchTodos(category));
        }
    };
}
```

### reflux

reflux 也一样，就是你在action中看着办。整个过程比redux要简单很多，action可以有阶段性事件，更新store要自己找地方存也是槽点（但我们不关心这个）。

```js
const actions = Reflux.createActions({
    list: {
        children: ['completed', 'failed']
    }
});

actions.list.listen(function (category) {
    service.todos(category)
        .then(this.completed)
        .catch(this.failed);
});
let store = Reflux.createStore({
    listenables: actions,

    onListCompleted(data) {
        todos = data;
        this.trigger(todos);
    },

    getData() {
        return todos;
    }
});
```

## 我觉得

我觉得，其实我们并不需要一个新的抽象，多个抽象多些理解成本，而且action的名字很天然挺好的，不管动作是要马上更新状态还是要去后端取数据，其实都是action。我们确实要保证对状态数据更新的同步性，promise保证不了，但我们可以在promise.then里面dispatch action，这时的操作一定是同步的。

```js
addAction('fetchList', page => {
    requestList(page).then(list => {
        this.dispatch('updateList', list);
    });

    return builder.set('list', null);
    // 或者可以this.dispatch('resetList')。我现在觉得，action里dispatch action也不是接受不了的事情
});
```

**Comment by otakustay** [comment]
几个疑问：

1. 如果这样的话，是否意味着Action分为“异步”和“同步”两类，是否允许一个Action根据情况自己选择不同分支返回Promise或builder，是否会造成[Zalgo问题](http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony)
2. 如果要明确分为“同步”和“异步”，那么在Action上是否需要一些标记来表示？如果有标记的话其实本身就是2个概念了
3. 既然允许action异步，那是否应该允许Action多次dispatch其它的action，如果需要，是否应该记录下一个action运行过程中到底dispatch了哪些，这个信息怎么串起来

我的建议：

1. 明确能标记Action是“生成builder”的还是“用于dispatch其它action”的，即将2者分开，就像redux中也是一个为纯对象一个为函数
2. 对于dispatch其它action的Action，让其签名为generator，不暴露dispatch函数，由这个generator每次yield一个[name, payload]的tuple，这样的优势有：
    1. 从函数的签名上就准确地将2种Action分开了
    2. 允许一次Action过程中产生多次的dispatch，且可以准确记录下来，最后一次使用return能标识action过程的结束，1:n本身是generator的定义

**Comment by errorrik** [comment]
1. Action 只能返回builder，或者毛都不返回就不更新状态。不能返回promise。Action内可以起异步行为，在callback或者then中dispatch other action（本来就只能这样，要不也没途径更新状态数据了）
2. 我觉得不用标记，这个action是同步还是异步，对应用开发者来说，根据名字就能知道了。对于程序，其实不care。多个抽象多个鬼，应用开发者要异步行为就在里面玩promise就好了。
3. 根据1，是允许的。至于怎么串起来，我把这事称为线索。实现方式已经想好了，还是需要actioncontext，上面提供dispatch方法和getState方法，其dispatch就能把线索串起来。

其实关键点在于，一个action只有一次更新状态数据的机会（可以放弃），并且是同步的（通过return builder）。所以不会破坏之前我们讨论的那些同步和依赖当前上下文原则，状态更新过程可追溯是可以做到的。

有一个问题是可能有大脑短路人士可能会这么写，那就变成依赖之前上下文了。但我觉得这种可以教育、文档、示例解决。

```js
addAction('fetchList', function (page) {
    let state = this.getState();
    requestList(page).then(list => {
        // 你以为currentPage还是你初恋时候的样子啊
        if (state.currentPage === page) {
            this.dispatch('updateList', list);
        }
    });

    return builder.set('list', null);
});
```

还有，上面的3中提到的actioncontext是有缺点的：你不能把箭头函数注册成action了。所以要不要考虑action的签名变成(payload, dispatch, getState) => builder?


另外，对于devtool对store的支持，要有两个tab：

1. 一个是状态更新的list，看到哪个action把状态从xx样变成了yy样
2. 一个是线索的list，看到是由哪个action发起了哪个action

两个tab之间要能点击对应上


这是我之前的想法。

**Comment by jinzhubaofu** [comment]
现在这样是不是限制了不能用 async / await ？

如果有 async / awati，最直接的写法应该类似这种吧：

```js
addAction('fetchList', async function (query) {
  try {
    store.loading = true;
    let result = await fetch(`xxx?query2string(query)`);
    store.list = result.list;
    store.loading = false;
  }
  catch (e) {
    store.loading = false;
    store.error = e;
  }
});
```

**Comment by jinzhubaofu** [comment]
唔，仔细想了一下，不知道是不是应该这么理解：

现在这个结构应该是 addAction('fetchList', builderCreator) 吧？

所以这个 builderCreator 应该只返回 builder，而不能返回 Promise 也不能是 generator 也不能是 async fucntion？

但是，如果遇到有异步的情况，这个 builderCreator 就有了副作用？

**Comment by errorrik** [comment]
> 很想在这一个action处理函数中把多次数据变更都做掉…
> 如果现在这样，只能 return builder 来修改数据，是会导致一个异步处理拆成多个 action 返回多个 builder 不太直观…

你这种写redux的还没适应不直观？

**Comment by jinzhubaofu** [comment]
唔，可能就是体位姿势还不太适应吧。再好好看看 erik 你提的这个也是可以接受的。

有个疑问，如果有 async / await 我这么干可以么？

```js

addAction('fetchList', async function (query) {
  try {
    this.dispatch('fetch-start');
    let list = await fetch(`/list?${query2string(query)}`);
    this.dispatch('update-list', list);
  }
  catch (error) {
    this.dispatch('fetch-error', error);
  }
}
addAction('fetch-start', function () {
  // ...
});
addAction('update-list', function (list) {
  return builder.set('list', list);
});
addAction('fetch-error', function (error) {
  return builder.set('error', error);
})
```

**Comment by errorrik** [comment]
我理解是可以的

**Comment by jinzhubaofu** [comment]
我这边在业务中遇到过这样一种相对复杂的 reduce 过程，大体上是我需要控制 reduce 的过程。在 redux 中我是这么干的：



```js

import {reducer as libReducer} from 'some-library';

function reduce(state, action) {
  state = libReducer(state, action);
  if (state.someField === 'xxx') {
    state = update(state, {
      $set: state.someField + 1
    });
  }
  return state;
}

```

在 san-store 的这种情况下，我应该怎么搞呢？

**Comment by errorrik** [comment]
```js
// 方法1
addAction('xxx', function () {
    // apply的意思是对原有的值应用更新，san-update有提供
    // 可以参考 https://facebook.github.io/react/docs/update.html
    let builder = updateBuilder().apply('someField', function (oldValue) {
        if (oldValue = xxx) {
            return oldValue + 'suffix';
        }

        return oldValue;
    });

    return builder;
});

// 方法2
addAction('xxx', function () {
    let builder = updateBuilder();

    // getState的方法怎么提供还没决定，这就随便意思下
    let state = getState('someField');

    if (state.someField) {
        builder = builder.set('someField', newValue);
    }

    return builder;
})
```

**Comment by errorrik** [comment]
好吧，我理解的有些问题。因为每次更新的上下文是当前state，所以你的办法只有，先dispatch一次action，让其变掉。你不能依赖一个还未变更的行为。

或者，你可以用一个函数封装公共部分，在action中调用它，用它生成updateBuilder

**Comment by jinzhubaofu** [comment]
> 所以你的办法只有，先dispatch一次action，让其变掉。你不能依赖一个还未变更的行为。

感觉这个是不行的。在同步的 reduce 的过程中不能再 dispatch 了吧？

> 你可以用一个函数封装公共部分，在action中调用它，用它生成updateBuilder

是这样么？

```js

import {builderFactory as libBuilderFactory} from 'some-lib';

addAction('xxx', function (...args) {

  // XXX 框架提供一套应对指定一系列 action 的 builder
  // 假设可以这么拿到 XXX 框架提供针对当前 action 的 builder
  let libBuilder = libBuilderFactory.getBuilderByAction('xxx', ...args);

  // 再把这个 builder 串联起来
  return builder.compose(
    libBuilder,
    function finalBuilderCreator() {
      let finalState = this.setState();
      if (finalState.xxx === 'xxx') {
        return builder.set('xxx', finalState.xxx + 1);
      }
    }
   );

});

```

**Comment by otakustay** [comment]
总的来说，我们将Action分为2类，第一类是对状态的更新的原子操作，第二类是通过一定的流程组织第一类的具体逻辑，使用dispatch调用第一类，这一点上我认为非常合理，我们写代码也是这样写的，先有封装原子逻辑的函数，再有调用这些函数组织而成的复杂逻辑

我想要的几点：

1. 一个异步的Action可以不限数量的进行dispatch
2. 能够标识Action的结束，即一个Action要有start - dispatch - dispatch - ... - dispatch - end这样的节点
3. 要知道dispatch和Action的关系

我整理一下有3种形式：

### dispatch函数

```
actions: {
    async selectItem(payload, {get, dispatch, done}) {
        dispatch('markSelectedItem', {id: payload.id}); // 记录当前选中的id

        if (!get('currentUesr.authorities').includes('viewItem')) {
            return;
        }

        dispatch('addLoading'); // 显示进度条

        try {
            let item = await fetch('...', payload);
            dispatch('viewSelectedItem', item);
        }
        finally {
            done('removeLoading'); // 结束进度条，done也可以不传参数
        }
    }
};
```

此处传递过去的dispatch函数是一个经过上下文环境bind的函数（类似AMD Loader的local require），因此只要调用了dispatch就能和相关的Action关联上

### context对象

```js
actions: {
    async selectItem(payload, context) {
        context.dispatch('markSelectedItem', {id: payload.id}); // 记录当前选中的id

        if (!context.get('currentUesr.authorities').includes('viewItem')) {
            return;
        }

        context.dispatch('addLoading'); // 显示进度条

        try {
            let item = await fetch('...', payload);
            context.dispatch('viewSelectedItem', item);
        }
        finally {
            context.done('removeLoading'); // 结束进度条，done也可以不传参数
        }
    }
};
```

与dispatch函数相比就是所有方法和context有this的关联，不能直接调用

### generator

```js
actions: {
    async *selectItem(payload, get) {
        yield ['markSelectedItem', {id: payload.id}]; // 记录当前选中的id

        if (!get('currentUesr.authorities').includes('viewItem')) {
            return;
        }

        yield 'addLoading'; // 显示进度条

        try {
            let item = await fetch('...', payload);
            yield ['viewSelectedItem', item];
        }
        finally {
            return 'removeLoading';
        }
    }
};
```

用yield和return天生代表dispatch和done，从语法上来支持

---

抛开环境考虑，我支持generator；从浏览器兼容性等综合考虑，我支持dispatch函数

**Comment by otakustay** [comment]
> 我这边在业务中遇到过这样一种相对复杂的 reduce 过程，大体上是我需要控制 reduce 的过程。在 redux 中我是这么干的：

简单来说，你想要部分属性的联动变化的功能？

**Comment by otakustay** [comment]
> 是这样么？

你要的这个功能现在不好做，因为san是需要diff来提供他视图更新的指导的，无论是builder还是函数如果套一层都会导致diff丢失

但如果你能保证`xxx`是一个纯计算的属性，本身不会被其它的逻辑set，那么这是简单的：

```js
import {createStore} from 'san-store';
import {composeAfter} from 'san-update';

let addComputed = builder => builder.apply('xxx', xxx => yyy);
let chainAction = action => (...args) => addComputed(action(...args));

let store = createStore();

let addAction = (name, action) => store.addAction(name, chainAction(action));

export default Object.create(
    store,
    {
        addAction: {value: addAction}
    }
);
```

但如果`xxx`既可能因为其它的属性变化而计算出来，也可能被业务逻辑set为其它值，那么我觉得这个state的设计是不是正确呢？

**Comment by jinzhubaofu** [comment]
> 简单来说，你想要部分属性的联动变化的功能？

核心点是这样：

我做了个框架，这个框架不但提供了 component 还提供了相关的 action creator / reducer / store structure。

比如一个复杂的表单 library，那么 library 对这一个系统都有内置的一套处理。当 input 被 focus 时，dispatch 一个 action {type: 'focus'}，store 中相应的状态会被更新为 {focus: true}；当 input 有任意输入时，触发 {type: 'touched'}，同时 store 状态也被更新 {touched: true}。

我希望能直接对接到我的业务系统。不做特殊处理，它也能跑；如果有特殊业务逻辑，也能扩展。

以下事情没有明白是什么意思：

1. 纯计算的属性

    还有不纯的么？属性都有哪些类型？

2. 本身不会被其它的逻辑set

    这个字段可以先被 lib builder set，后续还可能被我的业务 builder 再次 set。这个可能性不可预测，根据业务需要来。
  
    我猜是不是先后生成两个 diff ？最终，完成 reduce 时的结果一致应该就好了吧。

3. 那一大段代码看着好晕。。。

PS：dispatch + 1 

> dispatch 看上去没有 builder 了，和 redux 一毛一样啊！

**Comment by otakustay** [comment]
> 还有不纯的么？属性都有哪些类型？

纯计算属性的意思是这个属性的值永远是计算出来的，不存在直接对这个属性值的修改


> 这个字段可以先被 lib builder set，后续还可能被我的业务 builder 再次 set。这个可能性不可预测，根据业务需要来。

除非san-update支持某些方法让你知道当前对这个属性已经用了什么指令，不然你很难在这个基础上做

如果san-update提供支持（很简单的支持），那么你可以根据用的是apply还是其它指令来选择怎么封装，应该是能达到目标的

> 我猜是不是先后生成两个 diff ？最终，完成 reduce 时的结果一致应该就好了吧。

diff是在san-store内部处理的，所以对你来说没啥可能

> 那一大段代码看着好晕。。。

不就是重写了addAction函数，对每个action进行一次包装，在返回的builder上增加一个apply指令么……

**Comment by errorrik** [comment]
有几个疑问：

1. action function 为啥要async，不能再返回builder了？
2. 同步的action怎么做，毕竟大多数还是同步action，异步action是把一堆同步action串起来的途径。我觉得需要保证同步action要写得666

**Comment by errorrik** [comment]
> 比如一个复杂的表单 library，那么 library 对这一个系统都有内置的一套处理。当 input 被 focus 时，dispatch 一个 action {type: 'focus'}，store 中相应的状态会被更新为 {focus: true}；当 input 有任意输入时，触发 {type: 'touched'}，同时 store 状态也被更新 {touched: true}。

我理解，不是所有东西都要存应用状态里的，这应该是组件自身状态

**Comment by otakustay** [comment]
> action function 为啥要async，不能再返回builder了？

async是为了用await，纯语法问题。此类action肯定就不返回builder了，只会dispatch其它的

> 同步的action怎么做，毕竟大多数还是同步action，异步action是把一堆同步action串起来的途径。我觉得需要保证同步action要写得666

同步就是返回builder，和现在一样

异步action通过dispatch调用同步action，同步action就是对state的修改的一个方法，异步就是调n个方法形成一个业务流

**Comment by errorrik** [comment]
action调用时，如何判定这个action是同步还是异步的？

**Comment by otakustay** [comment]
> action调用时，如何判定这个action是同步还是异步的？

你只需判断这个action是不是返回了builder就行了，返回builder你就执行掉，不返回builder你就无视掉

**Comment by errorrik** [comment]
> 你只需判断这个action是不是返回了builder就行了，返回builder你就执行掉，不返回builder你就无视掉

1. 如果是这样，async是没用的
2. 但我不知道这个action到底done没done，因为不返回builder可能是我真的啥都不需要改。从实现业务功能来说，这么做没问题，但是未来做devtool追踪就不好搞了

**Comment by errorrik** [comment]
根据 @otakustay 上面提到的

> 1. 一个异步的Action可以不限数量的进行dispatch
> 2. 能够标识Action的结束，即一个Action要有start - dispatch - dispatch - ... - dispatch - end这样的节点
> 3. 要知道dispatch和Action的关系

1和3都是很自然的，关键是2，我们是不是非要知道end。如果不是的话，没问题，也不用done了，一样能拿到dispatch和action的关系以及顺序。

**Comment by otakustay** [comment]
> 如果是这样，async是没用的

async是在函数中能用await的必要条件，这是js语法上的事，本身和san-store是没关系的

> 1和3都是很自然的，关键是2，我们是不是非要知道end。如果不是的话，没问题，也不用done了，一样能拿到dispatch和action的关系以及顺序。

我觉得3并不是那么自然，你肯定要对dispatch做封装才可以实现3这一点

另外end能知道的话最好还是知道下，我觉得能有一个地方看到整个系统的running state还是很有必要的，同时也希望开发者能在流程的角度去思考，我们在程序上给予的限制就是done以后再调用dispatch会抛异常

**Comment by jinzhubaofu** [comment]
> 你要的这个功能现在不好做
> 不就是重写了addAction函数，对每个action进行一次包装，在返回的builder上增加一个apply指令么……

貌似还不是我想要的，我所希望的是 builder 的自由组合。确实有需要，求支持。

> 不是所有东西都要存应用状态里的，这应该是组件自身状态

不一定哎，看业务需要控制的粒度。

1. 如果是组件自行维护状态，那么整体状态就不要插手来管；只能给初始值，可以得到通知表单数据变化、提交事件通知，不能修改表单的任何数据、状态；
2. 如果要插手来管，那么就不要组件维护状态：也就是状态都放到应用状态里。你想怎么搞就怎么搞，反正符合我的 store structure 就好了。

一般最后开源组件都会妥协选后者：不让别人插手，那就给所有需求加属性，最终就是死路一条。

> Select 的 open 属性都暴露出来了，何况是大表单。

**Comment by otakustay** [comment]
> 貌似还不是我想要的，我所希望的是 builder 的自由组合。确实有需要，求支持。

composeBuilder并不好做，比如2个builder对同一个属性都有指令，其中一个是$pop一个是$set，那么最终的结果会是什么，这类的组合有非常多，除非我全给统一到set丢掉diff还有办法搞

**Comment by errorrik** [comment]
> 我觉得3并不是那么自然，你肯定要对dispatch做封装才可以实现3这一点

这事本来就打算做的

> 另外end能知道的话最好还是知道下，我觉得能有一个地方看到整个系统的running state还是很有必要的，同时也希望开发者能在流程的角度去思考，我们在程序上给予的限制就是done以后再调用dispatch会抛异常

done以后再调用dispatch的场景我觉得会很少，更多的是不调用done（我干吗要调用done，没吊用）

**Comment by otakustay** [comment]
> done以后再调用dispatch的场景我觉得会很少，更多的是不调用done（我干吗要调用done，没吊用）

我现在的设计都是为了结合以后devtool等工具来设想的，复用这些工具引导他们去调用done吧，比如我希望有一个列表能看到当前running中的所有action、每个action的不同dispatch之间的耗时等等

**Comment by errorrik** [comment]
> 我现在的设计都是为了结合以后devtool等工具来设想的，复用这些工具引导他们去调用done吧，比如我希望有一个列表能看到当前running中的所有action、每个action的不同dispatch之间的耗时等等

理想来说这样当然好，但是现实可能会变成因为没有调用done的习惯，所以devtool里面有好多action在running，头更疼了。

还有另外一种情况，异步的action dispatch了另外一个异步action，how to notice

**Comment by jinzhubaofu** [comment]
> composeBuilder并不好做，比如2个builder对同一个属性都有指令，其中一个是$pop一个是$set，那么最终的结果会是什么，这类的组合有非常多，除非我全给统一到set丢掉diff还有办法搞

所以。。。

```js
addActoin('xxx', action1, action2, ...);
```

builder 和 builder 不是静态 compose，action2 可以得到 action1 更新后的 state，再生成新的 diff 和 nextState ？

**Comment by otakustay** [comment]
> 理想来说这样当然好，但是现实可能会变成因为没有调用done的习惯，所以devtool里面有好多action在running，头更疼了。

我的想法倒是因为devtool里会有好多running的，所以他们会去用done呢- -


> 还有另外一种情况，异步的action dispatch了另外一个异步action，how to notice

每一次dispatch都有一个id + action name的上下文，我们的查找链是dispatch -> action -> id + action name -> another dispatch -> another action这样，应该是能溯源的……

**Comment by errorrik** [comment]
> 每一次dispatch都有一个id + action name的上下文，我们的查找链是dispatch -> action -> id + action name -> another dispatch -> another action这样，应该是能溯源的……

是可以，我在想有没有更好更天然的方式，比如return promise

```js
actions: {
    selectItem(payload, {get, dispatch}) {
        dispatch('markSelectedItem', {id: payload.id}); // 记录当前选中的id

        if (!get('currentUesr.authorities').includes('viewItem')) {
            return;
        }

        dispatch('addLoading');
        return fetch('...', payload).then(item => {
            dispatch('viewSelectedItem', item);
            dispatch('removeLoading')
        );
    }
};
```

**Comment by otakustay** [comment]
> builder 和 builder 不是静态 compose，action2 可以得到 action1 更新后的 state，再生成新的 diff 和 nextState ？

我反对为了非主流的需求把接口设计成这样，宁可我在san-update上给你提供combine的能力，并非不能做，丢掉diff也不一定不行

**Comment by otakustay** [comment]
> 是可以，我在想有没有更好更天然的方式，比如return promise

因为我们希望一个action能有多次的dispatch，所以promise这种1:1的并不是很合适，所以我才要generator啊，return就是结束

**Comment by jinzhubaofu** [comment]
> 宁可我在san-update上给你提供combine的能力，并非不能做，丢掉diff也不一定不行 

OK 靠谱，接受

**Comment by errorrik** [comment]
> 1. 如果是组件自行维护状态，那么整体状态就不要插手来管；只能给初始值，可以得到通知表单数据变化、提交事件通知，不能修改表单的任何数据、状态；
> 2. 如果要插手来管，那么就不要组件维护状态：也就是状态都放到应用状态里。你想怎么搞就怎么搞，反正符合我的 store structure 就好了。
>一般最后开源组件都会妥协选后者：不让别人插手，那就给所有需求加属性，最终就是死路一条。

我理解，组件状态是组件状态，你可以初始化或过程中通过属性去控制它，但是你写业务的时候需要控制的东西总是有场景的，比如业务场景的表单联动，那你要管理的是业务场景状态的state，并且在业务组件上绑定到表单组件的属性。

**Comment by errorrik** [comment]
> 因为我们希望一个action能有多次的dispatch，所以promise这种1:1的并不是很合适，所以我才要generator啊，return就是结束

then func里return promise不就是多次么，不过写起来没有这么淋漓畅快就是了

**Comment by otakustay** [comment]
> OK 靠谱，接受

我实际试了下还是有一点问题，使用san-update的一个限制是你无法复用a属性的状态去更新b属性，所以你要`if (a) b = c`本身是搞不了的

这在不做combine的时候没问题，因为你能拿到state所以只要在state上做if就行，但在combine有了之后，你的if判断的是“这个builder生效后的state”，这是你拿不到的……

**Comment by otakustay** [comment]
> then func里return promise不就是多次么，不过写起来没有这么淋漓畅快就是了

你其实就是把Promise当成最终的结束标识，这个Promise本身是不带有dispatch的效果的咯，倒也是可以……

**Comment by otakustay** [comment]
@jinzhubaofu 这边的需求，我想在store上可能需要一个“新state生成完后 - 覆盖原state”之间的hook，比如叫`onReceiveState`啥的，输入是`[state, diff]`输出是新的`[state, diff]`，默认实现为直接return

**Comment by errorrik** [comment]
嗯，promise本身不就是“我完事了，你上吧”

**Comment by otakustay** [comment]
> 嗯，promise本身不就是“我完事了，你上吧”

嘛反正promise本身就是一个受特殊处理的generator，这么做相比generator的好处是直接调用dispatch比`yield [name, payload]`更容易被人理解，我同意这样子

**Comment by errorrik** [comment]
好吧，那总结下：

1. 同步action返回builder
1. 异步action返回promise，完事算完
3. 参数就是(payload, {get, dispatch})，this free。（这里是叫get还是叫getState）

**Comment by errorrik** [comment]
> 这边的需求，我想在store上可能需要一个“新state生成完后 - 覆盖原state”之间的hook，比如叫onReceiveState啥的，输入是[state, diff]输出是新的[state, diff]，默认实现为直接return

我觉得 @jinzhubaofu 可以把代码和场景发出来，请 @otakustay 看看这样的场景是否有更好的设计

**Comment by jinzhubaofu** [comment]
> 我理解，组件状态是组件状态，你可以初始化或过程中通过属性去控制它，但是你写业务的时候需要控制的东西总是有场景的，比如业务场景的表单联动，那你要管理的是业务场景状态的state，并且在业务组件上绑定到表单组件的属性。

简单来个场景：重置表单。

表单的值应该是放到应用状态里，这没问题。除了值，以外的东西诸如 touched / dirty 这类数据的重置，无非就是两个方法：

要么是 dispatch('reset')， 要么是 getComponentInstance('form').reset();

前者是需要把组件状态也丢到应用状态里的；后者命令式 API。如果要选，我更喜欢前者。

**Comment by jinzhubaofu** [comment]
> 我觉得 @jinzhubaofu 可以把代码和场景发出来，请 @otakustay 看看这样的场景是否有更好的设计

收到，我 hi 上给灰大代码看看。

**Comment by otakustay** [comment]
另外补一句，还是强烈希望去掉addActions这个复数的方法，以支持使用Symbol做为action的名称

**Comment by errorrik** [comment]
> 简单来个场景：重置表单。

这个场景好。这就看你怎么界定“app state”了。

我认为，应用业务场景关心的数据，才能叫app state，一个input是不是focus，除非你的业务场景是focus时出现某个help的dialog，blur时消失，否则是不能通过app state维护的。

如果有reset的需求，我觉得组件本身做reset的抽象，通过命令式会更好些。当然如果组件没有这个抽象，你就只能通过全部状态放app state里来完成了。但你不觉得这样其实很蹩脚么

**Comment by errorrik** [comment]
> 另外补一句，还是强烈希望去掉addActions这个复数的方法，以支持使用Symbol做为action的名称

有啥区别么，symbol不能被for in出来，所以貌似要用symbol的直接用addAction就行了？

**Comment by errorrik** [comment]
> 参数就是(payload, {get, dispatch})，this free。（这里是叫get还是叫getState）

@otakustay 这个问题你觉得用那个好，我prefer getState

**Comment by otakustay** [comment]
> @otakustay 这个问题你觉得用那个好，我prefer getState

是否能不传参数拿到整个state，能的话就叫getState，不能的话就叫get吧

**Comment by errorrik** [comment]
ok，我想的是能。

**Comment by otakustay** [comment]
同步一下我和 @jinzhubaofu 的讨论结果，他想要的其实是这么个东西：

```js
import {foo as preExecute} from 'xxx/actions';

let myAction = (payload, context) => {
    let libBuilder = preExecute(payload, context);
    // 事实上这行代码后newState并没有进到store里面去
    let newState = libBuilder.build()(context.getState());

    // 在返回后，这个builder还会被执行一遍，也就是说这个Action的代价是执行2次builder，
    // 其中一次无论如何都只是为了得到新状态的中间变量，在性能上是完全浪费的
    if (!newState.xxx) {
        return libBuilder;
    }

    // 我来实现combine方法，作用就是在builder原来针对xxx的指令上再追加一个指令上去，新的指令得到的输入是上一个指令的输出
    return libBuilder.combine('xxx', {$set: 111});
};
```

虽然感觉有点hack但确实是可行的（本来在redux里复用reducer也蛮hack的感觉，我认了），只需要我的san-update加上combine这样的功能

**Comment by otakustay** [comment]
@jinzhubaofu 写了个方法可以把Action串起来，其中mergeDiff没有实现，可以参考[以前的实现](https://github.com/ecomfe/diffy-update/blob/master/src/merge.js)

```js
/**
 * 将多个Action连着在一起变成一个
 * 
 * @param Function [actions...] 多个需要连接在一起的Action，只接受同步Action
 */
let chain = (...actions) => payload => {
    let apply = state => actions.reduce(
        ([result, diffs], action) => {
            let withDiff = action(payload).buildWithDiff();
            let [newState, diff] = withDiff(result);
            return [newState, diffs.concat(diff)];
        },
        [state, []]
    );

    return {
        build() {
            return state => apply(state)[0];
        },

        buildWithDiff() {
            return state => {
                let [newState, diffs] = apply(state);
                return [newState, diffs.reduce(mergeDiff)];
            }
        }
    };
};
```

这方法和你组合reducer的方式是一样的，但有一个问题是redux最后只有一个reducer所以你可以在此基础上只做一次转换就行，但san-store本身是有多个action的，如果你要对所有的action都生效，需要自己实现san-store的addAction方法

**Comment by jinzhubaofu** [comment]
> 我认为，应用业务场景关心的数据，才能叫app state，一个input是不是focus，除非你的业务场景是focus时出现某个help的dialog，blur时消失，否则是不能通过app state维护的。

这个说的非常对，对于具体业务来说，哪些数据在 app state 哪些不在，那是必然有个度的。

但是作为框架来说，这个度很难把握。举个例子：对于一个框架来说，怎么才能确定使用者关不关心 focus 状态呢？

1. 只要有一个场景需要用到 focus 那就放到 app state ？
2. 60% 使用者对这个有需要就放到 app state 中？
3. 要不每年大家来投个票，看看状态 focus 要不要了？
4. 或者我就做一个业务线的框架，或者我叫 PM 不要设计我的框架不支持的交互出来。。。

这个问题我纠结了很久之后，基于 redux 是这样做：

1. Uncontrolled

    如果使用者觉得我这框架的默认行为还够用，那么框架可以自行维护状态。使用者只能给初始值，拿最终的结果，过程是不能插手的。

2. Controlled

    如果使用者觉得这个框架的默认行为不够用，要做扩展，那么我把框架内部所有的状态都给你：我把我的内部状态完整地挂载你的 app state 上，同时给你所有的 component / reducer / selector / action 。使用者按需要自由组合就好，加功能简单，去掉功能也很简单。

> 如果有reset的需求，我觉得组件本身做reset的抽象，通过命令式会更好些

我们现在不是整体都是『数据驱动』的指导思想么？为啥这时候突然就要求我提供 API 了呢？这不是更奇怪么？组件自行维护的状态就要用一堆 API 喽？有越复杂的内部状态，就有越复杂的 API 喽？

对于一个复杂的模块，这样下去 API 越来越多越来越复杂。如果有 `reset`，没准儿就会有人需要有 `resetFields(...fields)`。最不想看到的就是：『我们这个场景需要一个 `hide(...fields)` 的 API 求支持！』

但是如果是基于一套 app state structure 约定，那么就很简单了：你想要什么奇怪的逻辑就加一套 action + reducer 就好了。

框架要做的只是提供这些东西，来覆盖常用情景就可以：
1. state structrue
    > 基本固定，需要好好设计
1. action 
    > 一堆 plain object，覆盖我内置所有的业务抽象，{type: focus} {type: touch} {type: change}
    > 想用就用，不想用自己重新搞一个；新搞的当然你自己写 reducer。
1. action creator
    > 提供内置的所有业务抽象标准 actions.focus() / actions.change()
    > 纯函数自由组合 so easy! 逻辑分支、循环、异步请便。
1. reducer
    > 覆盖内置 action 的处理
    > 纯函数自由组合 so easy！逻辑分支、循环、异步请便。
1. component
    > 标准接口，完全可替换。

> redux 虽然很烦，但是基本上想去的地方都能到，而且还挺方便。。。

最终的感悟是：reducer （数据状态流转逻辑）才是『数据驱动』的 core 呀！是需要复用的呀！

基于以上，我才需要支持 `builder.chain()`，也就是 action / reducer 的自由组合的功能力。
